spring.application.name=parcel
spring.config.import=optional:configserver:http://localhost:8888/
server.port=8081

# # Datasource
# spring.datasource.url=jdbc:postgresql://localhost:5432/zipcode_db
# spring.datasource.username=diego_papu
# spring.datasource.password=diego_pap1

# # JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # config OpenAPI
# # Swagger UI
# springdoc.api-docs.path=/api-docs
# springdoc.swagger-ui.path=/swagger-ui.html